# Generated by Django 4.1.1 on 2023-03-29 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayingGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(default='My group', max_length=60)),
                ('monthly_cost', models.DecimalField(decimal_places=2, default='0', max_digits=6)),
                ('next_payment_date', models.DateField(auto_now_add=True)),
                ('manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Subscriber Name', max_length=60)),
                ('iban', models.CharField(default='Subscriber Iban', max_length=60, unique=True)),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('group', models.ManyToManyField(to='dashboard.payinggroup')),
                ('manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(default='service', max_length=60)),
                ('whole_service_name', models.CharField(default='Service name', max_length=60)),
                ('hex_color_without_hashtag', models.CharField(default='ffffff', max_length=6)),
                ('manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_payment', models.DateField(auto_now_add=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.subscriber')),
            ],
        ),
        migrations.AddField(
            model_name='payinggroup',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.service'),
        ),
    ]
