# Generated by Django 4.1.1 on 2023-03-24 14:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayingGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=60, null=True)),
                ('monthly_cost', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('next_payment_date', models.DateField(default=datetime.datetime(2023, 3, 24, 14, 8, 42, 354183, tzinfo=datetime.timezone.utc))),
                ('manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, null=True)),
                ('iban', models.CharField(max_length=60, null=True, unique=True)),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True)),
                ('group', models.ManyToManyField(to='dashboard.payinggroup')),
                ('manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(default='service', max_length=60, null=True)),
                ('whole_service_name', models.CharField(default='Service name', max_length=60, null=True)),
                ('hex_color_without_hashtag', models.CharField(default='ffffff', max_length=6)),
                ('manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_payment', models.DateField(default=datetime.datetime(2023, 3, 24, 14, 8, 42, 356181, tzinfo=datetime.timezone.utc), null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.subscriber')),
            ],
        ),
        migrations.AddField(
            model_name='payinggroup',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.service'),
        ),
    ]
