# Generated by Django 4.1.1 on 2022-09-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='iban',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='payinggroup',
            name='nazov_skupiny',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='meno',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
