# Generated by Django 4.1.1 on 2022-09-24 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_subscriber_iban_alter_payinggroup_nazov_skupiny_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='zaplatene_stav',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='posledna_platba_suma',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.subscriber')),
            ],
        ),
    ]
