# Generated by Django 4.1.1 on 2023-03-25 13:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_alter_payinggroup_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payinggroup',
            name='next_payment_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 25, 13, 46, 37, 135322, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_of_payment',
            field=models.DateField(default=datetime.datetime(2023, 3, 25, 13, 46, 37, 138325, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
