# Generated by Django 4.1.1 on 2023-03-25 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_payment_manager_alter_payinggroup_next_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payinggroup',
            name='next_payment_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 25, 13, 48, 4, 361912, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_of_payment',
            field=models.DateField(default=datetime.datetime(2023, 3, 25, 13, 48, 4, 363911, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
