# Generated by Django 4.1.1 on 2022-09-24 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_payinggroup_hex_color_without_hashtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazov_sluzby', models.CharField(max_length=60, null=True)),
                ('hex_color_without_hashtag', models.CharField(default='ffffff', max_length=6)),
            ],
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='posledna_platba',
            new_name='platba',
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='posledna_platba_suma',
            new_name='platba_suma',
        ),
        migrations.RemoveField(
            model_name='payinggroup',
            name='hex_color_without_hashtag',
        ),
        migrations.AddField(
            model_name='payinggroup',
            name='sluzba',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.service'),
            preserve_default=False,
        ),
    ]
