# Generated by Django 4.1.1 on 2022-09-24 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_service_rename_posledna_platba_subscriber_platba_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payinggroup',
            name='sluzba',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.service'),
        ),
    ]
