# Generated by Django 4.1.1 on 2022-10-04 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_payinggroup_dalsia_platba_datum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payinggroup',
            name='dalsia_platba_datum',
            field=models.DateField(default=datetime.datetime(2022, 10, 4, 7, 45, 19, 756756, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='datum_platby',
            field=models.DateField(default=datetime.datetime(2022, 10, 4, 7, 45, 19, 758775, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='skupina',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='skupina',
            field=models.ManyToManyField(to='dashboard.payinggroup'),
        ),
    ]
