# Generated by Django 4.1.1 on 2022-10-04 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_payinggroup_dalsia_platba_datum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payinggroup',
            name='dalsia_platba_datum',
            field=models.DateField(default=datetime.datetime(2022, 10, 4, 7, 47, 58, 65349, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='datum_platby',
            field=models.DateField(default=datetime.datetime(2022, 10, 4, 7, 47, 58, 67350, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='dlh',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='zaplatene_dokopy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
