# Generated by Django 4.1.1 on 2022-10-04 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_payinggroup_dalsia_platba_datum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='platba_suma',
        ),
        migrations.AddField(
            model_name='payment',
            name='platba_suma',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='payinggroup',
            name='dalsia_platba_datum',
            field=models.DateField(default=datetime.datetime(2022, 10, 4, 7, 48, 56, 810328, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='datum_platby',
            field=models.DateField(default=datetime.datetime(2022, 10, 4, 7, 48, 56, 813325, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
