# Generated by Django 4.1.1 on 2022-10-04 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_subscriber_platba_suma_payment_platba_suma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payinggroup',
            name='dalsia_platba_datum',
            field=models.DateField(default=datetime.datetime(2022, 10, 4, 7, 57, 17, 753906, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='datum_platby',
            field=models.DateField(default=datetime.datetime(2022, 10, 4, 7, 57, 17, 755892, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='iban',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
    ]
