# Generated by Django 4.1.1 on 2022-10-04 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_subscriber_ma_mat_zaplatene_dokopy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cely_nazov_sluzby',
            field=models.CharField(default=models.CharField(default='sluzba', max_length=60, null=True), max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='payinggroup',
            name='dalsia_platba_datum',
            field=models.DateField(default=datetime.datetime(2022, 10, 4, 12, 16, 59, 505058, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='datum_platby',
            field=models.DateField(default=datetime.datetime(2022, 10, 4, 12, 16, 59, 507056, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='nazov_sluzby',
            field=models.CharField(default='sluzba', max_length=60, null=True),
        ),
    ]
