# Generated by Django 4.1.1 on 2022-10-04 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_service_cely_nazov_sluzby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payinggroup',
            name='dalsia_platba_datum',
            field=models.DateField(default=datetime.datetime(2022, 10, 4, 12, 19, 12, 980829, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='datum_platby',
            field=models.DateField(default=datetime.datetime(2022, 10, 4, 12, 19, 12, 983798, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='cely_nazov_sluzby',
            field=models.CharField(default='Názov služby', max_length=60, null=True),
        ),
    ]
