# Generated by Django 4.1.1 on 2022-11-17 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_payment_active_alter_payinggroup_dalsia_platba_datum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='ma_mat_zaplatene_dokopy',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='zaplatene_dokopy',
        ),
        migrations.AlterField(
            model_name='payinggroup',
            name='dalsia_platba_datum',
            field=models.DateField(default=datetime.datetime(2022, 11, 17, 14, 38, 16, 960747, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='datum_platby',
            field=models.DateField(default=datetime.datetime(2022, 11, 17, 14, 38, 16, 964748, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
