# Generated by Django 4.1.1 on 2022-11-17 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_remove_subscriber_ma_mat_zaplatene_dokopy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payinggroup',
            name='dalsia_platba_datum',
            field=models.DateField(default=datetime.datetime(2022, 11, 17, 14, 42, 36, 572561, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='datum_platby',
            field=models.DateField(default=datetime.datetime(2022, 11, 17, 14, 42, 36, 574562, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
