# Generated by Django 4.1.1 on 2022-11-18 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_payinggroup_dalsia_platba_datum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payinggroup',
            name='dalsia_platba_datum',
            field=models.DateField(default=datetime.datetime(2022, 11, 18, 9, 51, 12, 595326, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='datum_platby',
            field=models.DateField(default=datetime.datetime(2022, 11, 18, 9, 51, 12, 598325, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
